#ifndef BEAMLINE_CONFIG_H
#define BEAMLINE_CONFIG_H

// Network configuration
#define BEAMLINE_PORT 5064
#define BEAMLINE_BACKLOG 10
#define BEAMLINE_MAX_CLIENTS 32

// Buffer sizes
#define BEAMLINE_CMD_BUFFER_SIZE 1024
#define BEAMLINE_RESPONSE_BUFFER_SIZE 4096

// PV limits
#define BEAMLINE_MAX_PVS 128
#define BEAMLINE_PV_NAME_MAX 64

// Timing
#define BEAMLINE_SELECT_TIMEOUT_MS 100
#define BEAMLINE_MOTOR_UPDATE_INTERVAL_MS 10

#endif // BEAMLINE_CONFIG_H
